import { MetadataRoute } from 'next'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Mike Yukhtenko',
    short_name: 'Mike',
    description: 'Product Designer, Mentor, Lecturer',
    start_url: '/',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#ffffff',
    icons: [
      {
        src: '/icon.svg',
        sizes: 'any',
        type: 'image/svg+xml',
      },
      {
        src: '/apple-icon.png',
        sizes: '512x512',
        type: 'image/png',
      },
      {
        src: '/icon.png', // Fallback if generated by Next.js, or reuse apple-icon if desired
        sizes: '512x512',
        type: 'image/png',
      },
    ],
  }
}
